<?php
add_action('acf/include_fields', function () {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_682b32b938501',
        'title' => 'Contenu des pages',
        'fields' => array(
            array(
                'key' => 'field_682b32b9109b0',
                'label' => 'Contenu',
                'name' => 'main-content',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'pagination' => 1,
                'rows_per_page' => 5,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Ajouter un élément',
                'sub_fields' => array(
                    array(
                        'key' => 'field_682b35dc109b5',
                        'label' => 'Type de	contenu',
                        'name' => 'content_type',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '30',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'text' => 'Section de texte',
                            'article' => 'Articles',
                            'cta_donation' => 'Appel aux dons',
                            'site' => 'Sites/Maisons d’accueil',
                        ),
                        'default_value' => 'text',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_682b32b9109b0',
                    ),
                    array(
                        'key' => 'field_682b356d109b3',
                        'label' => 'Titre de la section',
                        'name' => 'title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_682b32b9109b0',
                    ),
                    array(
                        'key' => 'field_682b359b109b4',
                        'label' => 'Contenu de texte',
                        'name' => 'text_content',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => 'br',
                        'parent_repeater' => 'field_682b32b9109b0',
                    ),
                    array(
                        'key' => 'field_682b3a96109bb',
                        'label' => 'Type d\'article',
                        'name' => 'article_type',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_682b35dc109b5',
                                    'operator' => '==',
                                    'value' => 'article',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'holiday' => 'Vacances',
                            'funding' => 'Financements',
                        ),
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_682b32b9109b0',
                    ),
                    array(
                        'key' => 'field_68318a6c243b3',
                        'label' => 'Identifiant de la section',
                        'name' => 'section_id',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Doit être en minuscules, sert à ajouter une ancre nommée sur la page. Ne pas toucher, à moins de vous renseigner sur les ancres nommées des hyperliens.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_682b32b9109b0',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
                array(
                    'param' => 'post_type',
                    'operator' => '!=',
                    'value' => 'contact_message',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_683983290a489',
        'title' => 'Contenu des sites/maisons',
        'fields' => array(
            array(
                'key' => 'field_6839be4c172a5',
                'label' => 'Sous-titre',
                'name' => 'single_site_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '%title%',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6839be7e172a6',
                'label' => 'Texte d\'en-tête',
                'name' => 'single_site_text_content',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Le Vieux Moulin est situé à Strainchamps, accueillant actuellement 18 jeunes, avec 24 personnes en effectif, comprenant les éducateurs et le personnel d’entretient. Malgré son apparence rustique, le bâtiment possède toutes les installations nécessaires au développement des enfants, bien que certains éléments sont datés.',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_68398329043f2',
                'label' => 'Images du site',
                'name' => 'site_images',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Ajouter un élément',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6839836c043f3',
                        'label' => 'TItre',
                        'name' => 'title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_68398329043f2',
                    ),
                    array(
                        'key' => 'field_6839838f043f4',
                        'label' => 'Image',
                        'name' => 'img',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                        'parent_repeater' => 'field_68398329043f2',
                    ),
                    array(
                        'key' => 'field_683983be043f5',
                        'label' => 'Contenu de texte',
                        'name' => 'text_content',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                        'parent_repeater' => 'field_68398329043f2',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'site',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_682b28fcdf585',
        'title' => 'Header sliders',
        'fields' => array(
            array(
                'key' => 'field_682c2f4f68161',
                'label' => 'Premier header',
                'name' => 'thumbnail_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Ces deux premiers titre et textes de contenu iront de paire avec l’image mise en avant. Vous pourrez en rajouter d\'autres à tout moment via le tableau, mais il faut au moins celui-ci en haut de page.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Bienvenue sur le site du Vieux Moulin !',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_682c2fe468162',
                'label' => 'Contenu du premier header',
                'name' => 'thumbnail_text_content',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Le vieux moulin est une SRG s’occupant d’enfants retirés à leur famille pour des raisons juridiques. Elle accueille actuellement 34 jeunes.
	Notre travail est de permettre à ces jeunes de grandir dans un environnement le plus sain possible, vivre la ville que tout enfant mérite. Nous faisons de notre mieux pour donner aux jeunes un nouveau cadre dans lequel s’épanouir et grandir en bonne santé. Aidez-nous. Faites un don. Pour les enfants.',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_682b28fdfc25e',
                'label' => 'Slider',
                'name' => 'slider',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Ajouter un élément',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_682b2943fc25f',
                        'label' => 'Titre',
                        'name' => 'title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Bienvenue sur le site du Vieux Moulin !',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_682b28fdfc25e',
                    ),
                    array(
                        'key' => 'field_682b2969f3a27',
                        'label' => 'Texte',
                        'name' => 'text_content',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Le vieux moulin est une SRG s’occupant d’enfants retirés à leur famille pour des raisons juridiques. Elle accueille actuellement 34 jeunes.
	Notre travail est de permettre à ces jeunes de grandir dans un environnement le plus sain possible, vivre la ville que tout enfant mérite. Nous faisons de notre mieux pour donner aux jeunes un nouveau cadre dans lequel s’épanouir et grandir en bonne santé. Aidez-nous. Faites un don. Pour les enfants.',
                        'maxlength' => '',
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => 'br',
                        'parent_repeater' => 'field_682b28fdfc25e',
                    ),
                    array(
                        'key' => 'field_682b2aaff3a28',
                        'label' => 'Image',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'medium',
                        'parent_repeater' => 'field_682b28fdfc25e',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
                array(
                    'param' => 'post_type',
                    'operator' => '!=',
                    'value' => 'contact_message',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '!=',
                    'value' => 'post',
                ),
                array(
                    'param' => 'post_type',
                    'operator' => '!=',
                    'value' => 'contact_message',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_6836e1e7e196d',
        'title' => 'Partenariats',
        'fields' => array(
            array(
                'key' => 'field_6836e82e57527',
                'label' => 'Titre partenariats',
                'name' => 'partnerships_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Nos partenariats',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6836e1e8bd521',
                'label' => 'Partenariats',
                'name' => 'partnership_rows',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Ajouter un élément',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6836e203bd522',
                        'label' => 'Nom du partenaire',
                        'name' => 'name',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_6836e1e8bd521',
                    ),
                    array(
                        'key' => 'field_6836e215bd523',
                        'label' => 'Logo du partenaire',
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '.svg, .png',
                        'preview_size' => 'medium',
                        'parent_repeater' => 'field_6836e1e8bd521',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '28',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_683614237bec6',
        'title' => 'Texte de vignette',
        'fields' => array(
            array(
                'key' => 'field_683614232e949',
                'label' => 'Texte de vignette',
                'name' => 'article_thumbnail_text',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'max. 2 lignes',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => 300,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_6835850b15bf2',
        'title' => 'Texte du formulaire de dons',
        'fields' => array(
            array(
                'key' => 'field_6835850b9862d',
                'label' => 'Titre',
                'name' => 'donation_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Faire un don',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6835853d9862e',
                'label' => 'Texte',
                'name' => 'donation_text',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_684b224d66234',
                'label' => 'QR code',
                'name' => 'donation_qr_code',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-donation.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});

